# Generated by Django 5.1.2 on 2024-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_vote_unique_together_vote_unique_thread_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='forumthread',
            unique_together={('slug', 'title')},
        ),
    ]
