# Generated by Django 5.1.2 on 2024-12-08 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forumthread_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forumthread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
