# Generated by Django 5.1.2 on 2024-12-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forumthread_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='vote_count',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
