# Generated by Django 5.1.2 on 2025-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
